# Generated by Django 5.1.6 on 2025-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_remove_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.TextField(max_length=100),
        ),
    ]
