# Generated by Django 5.1.6 on 2025-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_alter_appointment_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.TextField(),
        ),
    ]
